@startuml
start
    :ユーザーがサイトのトップページに行く;
    if (ユーザーがログインしていなかったら) then
        :ログイン画面に行く;
    endif
    :掲示板一覧に行く;
    :掲示板一覧から任意の掲示板クリックした時;
    if (ユーザー設定をしていなかったら) then
        :ユーザー設定画面に飛ぶ;
    endif
    :掲示板に入室;
    if (初めて掲示板を利用する場合は) then
        :掲示板利用案内のモーダルを表示する;
    endif
    :掲示板の各機能は掲示板機能図を参照;
stop
@enduml
