@startsalt
{+
    {^"マイページ"
        {^"ユーザー情報"
            [編集する]
            名前|たく
            --|..
            自己紹介|適当な自己紹介
            --|..
        }
        {^"所持キャラクター"
            {+
                [編集する][削除する]
                名前|たく
                --|..
                種族（種別）|ポケモン
                --|..
                性別|オス
                --|..
                年齢|20
                --|..
                詳細|背後そのものであるが…
                --|..
            }
            ~~
            {+
                [編集する] [削除する]
                名前|おとか
                --|..
                種族（種別）|ポケモン
                --|..
                性別|オス
                --|..
                年齢|25
                --|..
                詳細|元々はわいわいタウンの出身で…
                --|..
            }
        }
    }
}
@endsalt
